---
title: "Topic proposal for Final Project in Welfare State & Demographic Change"
author: "Paulo Kalkhake"
date: "7 October, 2016"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
##The Home Equity Effect and Fertility Rates - Evidence for Germany

Fertility is a complex and many-layered decision for individuals, not solely based on monetary determinants. Nevertheless, having children is costly, and individuals’ fertility decisions is closely linked to economic factors. Since a family requires extra space for their newborn, housing costs represent a substantial proportion of households’ expenses in having children. However, a change in housing costs, affect people and their decision-making in different ways. On the one hand, renters and individuals that what to buy estate are suffer from rising higher housing costs. On the other hand, when the price of housing goes up, the perceived wealth of home-owners rises (home equity effect). And vice versa. This leads one to wonder about the impact of the housing costs on fertility and family-size decisions. 

Recent research has examined this link between housing costs and fertility outcomes. A paper by Lisa Dettling and Melissa Kearney (2015) examined whether home prices affects fertility rates in the US. The authors used data from 1990 to 2007, and housing price indices to explore equity/fertility correlations. Their results suggest that a ten percent increase in house prices would lead to a four percent increase in births among home owners, and a roughly one percent decrease among non-owners.

Given a brief literature review we would argue that: 
  
> H1: When housing costs, i. e. rents or/and real estate prices, rise, the price of having children also rises, which delays (first) childbearing or to have fewer children altogether, for people that are not home-owners. Conversely, increases in property prices should have a negative effect on fertility rates for tenants, as the prospect of being able to buy a house recedes. 

> H2: For a proportion of the population is housing a substantial portion of their household wealth. Increases in property prices will have a perceived wealth effect that leads to an increase in fertility rates and family-size for existing homeowners.

#Methodology

control variables: age, education, ethnicity, labor market participation

Our Paper would enrich the discussion by looking for evidence in Germany. For policy makers, it could be interesting to isolate this single determinant of fertility decision making rationale, to implement more encouraging and family friendly policies.



