---
title: "Proposal: The Effect of Airbnb's Market Entry on Hotels in Berlin: A Regression Discontinuity Approach"
author: "Paulo Kalkhake & Dan Murphy"
date: "27 October 2016"
output: pdf_document
toc: FALSE
bibliography: Final_Bibliography.bib
linestretch: 1.5
number_sections: TRUE

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

##Motivation & Research Questions

The effects of Airbnb on the Berlin housing market has recently been the subject of a great deal of scrutiny. In 2014, the city passed a law that forbade renting out entire apartments to tourists on Airbnb. This came in response to an unprecedented 56 percent rise in rents in Berlin between 2009 and 2014, for which Airbnb and other online hosting platforms received some of the blame [@France-Presse:2016aa]. The city's law was widely welcomed by Berliners hoping to slow the forces of gentrification, but it was also welcomed by another Airbnb victim in Berlin; the hotel industry. 

While Berliners fought tourists for apartments, hotels were quietly fighting Airbnb for tourists. That's a real challenge for the long-time incumbents, whose average price of 80 euros per night cannot compete with the average Airbnb price of 55 euros per night [@Alsino-Skowronnek:2015aa]. To make matters worse, the rise of Berlin as the place to be happened to coincide with the rise of Airbnb as the place to stay. This prevented the hotels of Berlin from fully realizing profits that were, in their minds, rightfully theirs. Airbnb, however, claims that their service is complementary, since 77 percent of Berlin's Airbnb listings are outside of the main hotel districts [@Airbnb:2015aa]. 

In this paper we will seek to illustrate the magnitude of the "Airbnb effect" on hotels in Berlin. To that end, two hypotheses will guide our thinking. 

> *H1: The higher the Airbnb supply in a given district in Berlin, the lower the hotel occupancy rate will be in that same district.*

> *H2: Since Airbnb's listings are concentrated in districts with low hotel density, the effect of substitution will be more pronounced in those districts.*

##Literature Review

While the literature on the effect of Airbnb on hotels is quite limited, there is one prominent paper that helped inspire this investigation. In their paper, @zervas2016rise used a difference in differences method (DID) to measure the impact that Airbnb's presence had on Texas hotel revenue, and how this impact differed by region and over time. They found that a 10 percent size increase of the Airbnb market in Texas resulted in a .39 percent decrease in hotel revenue. This effect varied widely by region, however. Austin, for example showed a 8 to 10 percent impact on hotel revenue. Zervas et al. also went on to investigate the impact of Airbnb's presence on different types of hotels and how that presence may effect hotel pricing models. They found that hotels with lower prices are more affected than higher priced hotels, and that Airbnb has significantly hindered hotels' ability to raise prices during high demand periods. 

Some literature does exist on Airbnb's entry into Berlin, however much of this is focused on the impact on rents in the city. @schafer2016misuse, for example, found that 5,555 residential apartments are currently being misused for Airbnb in Berlin. However, as the *Zweckentfremdungsverbot* (Airbnb misuse law) came into effect this year, the main focus of this issue is likely to be enforcement going forward. In terms of our focus, a working paper by @storsmotives indicates that the motives for a tourist to use Airbnb rather than a hotel are both monetary and otherwise. In fact, they found that guests' expectations of having a more authentic, personal experience during their stay were just as important as the monetary aspect. This suggests that the hotel industry in Berlin is not only being undercut in pricing, but also outclassed in the experience they provide. 

##Data
Our investigation will utilize data from two different sources. First, we will use monthly tourism survey data from the Statistical Information System Berlin Brandenburg [@Brandenburg:2016aa] and the Regional Database Germany [@Germany:2015aa]. These data sets provide reliable information about the trends in tourism in Berlin between 2010 and 2014. The surveys are carried out at the beginning of each month and refer to the reporting period of the previous month. The results are organized regionally according to districts and municipalities, allowing us to have specific data for each of the ten districts in Berlin. We will use this geographic specificity to take a close look at the relationship between hotel occupancy rate and Airbnb supply in each of Berlin's districts. 

Second, our paper uses data from *InsideAirbnb.com*. This data was extracted from the Airbnb site between 18 July 2015 and 6 January 2016. It includes listings from more than 15 cities in 16 countries, one of them being Berlin [@Airbnb:2016aa]. While using data directly extracted from Airbnb's website or API for our research would be preferable, it is not publicly available. However, the data extracted from *InsideAirbnb.com* is an appropriate alternative. We have detailed information on all Airbnb listings for Berlin between 2010 and 2014, including calendar data and review data. This allows us to conduct comparable time based analytics in concert with our hotel data. 

Our most significant data challenge is the absence of precise listing availability data during our period of interest. However, in keeping with the @zervas2016rise methodology, we will use review data as a proxy with which we can establish whether or not a listing was available in a given month. The paper acknowledges that while this is not ideal, Airbnb itself is unable to produce exact availability data due to the prevalence of "stale vacancies" on the site. That is, listings whose owners have not accurately updated their availability.

##Methodology

Unlike @zervas2016rise, we cannot use hotel revenue as our main unit of analysis due to data limitations. Instead, our analysis will focus on hotel occupancy rates. Also unlike the model used by the authors, our analysis cannot take advantage of a treatment and control region accounting for the different Airbnb market entry patterns. Instead, we propose the use of a Regression Discontinuity Model (RDM) [@jacob2012practical]. 

By introducing a binary variable which is equal to one for all observations after Airbnb's market entry in Berlin and interacting that variable with all regressors in our model, we account for all the changes in hotel occupancy rates before and after Airbnb's market entry in Berlin, i. e. the dicontinuity at market entry. 

Taking the arguments above into account, our main specification for our proposal would look like this:

> (1) ${\log OccupRate}_{it} = \beta _i * \log Abb_{it} + \tau _i + \beta _j * X_j + \varepsilon _{it}$

Here, log *OccupRate* is the occupancy rate for all hotels in district *i* at time *t*. Log *Abb* is the log of the approximated total number of Airbnb listings available in district *i* at time *t*. Further, we control for economic conditions (unemployment rate and GDP per capita at federal level) and a district-specific linear time trend to account for unobserved heterogeneous variation across districts by using a month-year time dummy *$\tau$*.

##Expectations
Conducting our research, we expect to produce empirical evidence that quanitifies the effect of Airbnb's entry in Berlin on hotel occupancy rates.  


\newpage
##Bibliography